### ISSUE TITLE
Images are not loading if browser is not in focus

### ISSUE THREAD

**Issue by clibequilibrium** [zerodevx/svelte-img#36]
Hello,

Thank you so much for this package, it is very useful for my project.
I am currently having an issue on dual screen where my images are not transitioning from lqip to an actual image. The issue persists for both standard Img component and FxReveal. Pleasee see the [video ](https://streamable.com/fzu4wi)

I am using tailwind and postcss for animation of the elements.

```Js
<script>
	 import Img  from '@zerodevx/svelte-img';
	const modules = import.meta.glob('$lib/images/worlds/*.*', {
		import: 'default',
		eager: true,
		query: { fit: 'cover', as: 'run' }
	});
	const images = Object.entries(modules).map((i) => i[1]);
</script>

<div class="relative aspect-video">
	<section class="grid grid-cols-2 gap-4 md:grid-cols-2 ">
		{#each images as image, i}
			<div class={i % 2 === 0 ? 'anim-float-gallery-up' : 'anim-float-gallery-down'}>
				<Img class="h-auto max-w-full rounded-lg" src={image} alt="" />
			</div>
		{/each}
	</section>
</div>

<style lang="postcss">
	.anim-float-gallery-up {
		animation: float-up 30s ease-in-out infinite;
	}

	.anim-float-gallery-down {
		animation: float-down 30s ease-in-out infinite;
	}
	/* prettier-ignore */
	@keyframes float-up {
		0% { transform: translateY(-100px); }
		50% { transform: translateY(-700px); }
		100% { transform: translateY(-100px); }
	}
	/* prettier-ignore */
	@keyframes float-down {
		0% { transform: translateY(-660px); }
		50% { transform: translateY(-60px);}
		100% { transform: translateY(-660px); }
	}
</style>
```
Do you have an idea of why it might happen? Thank you !

**Comment by zerodevx** [comment]
Hey there. First of all, the `eager` in `import.meta.glob` is a Vite construct as described [here](https://vitejs.dev/guide/features.html#glob-import) - nothing to do with the image's `loading` attribute. Generally, you'll want to set `eager: true` when importing using Vite's `import.meta.glob()` feature because this technique is simply synthetic sugar (instead of writing import statements for every image).

Regarding LQIP, the original intention is to display it only for the times when the full-size image is still loading. In fact, in the ideal case (fast internet connection, normal scrolling), images should just be exactly that - images. And ideally users shouldn't even see the low quality version. 

I saw your video. Your site looks good! As to why some images appear with LQIP and some without, unfortunately I don't think it's something we can control. The browser handles the image download, so this "transition" appears only in cases when image is still downloading. By setting `loading="eager"` on the `<img>` tag, we are just hinting to browsers to prioritise the download.

Hopefully this helps to clarify.

**Comment by clibequilibrium** [comment]
Thank you @zerodevx it made sense ! 
I will keep digging to browser specifics to understand how I can still download images when the browser is not focused. 

Thank you so much for the detailed answer
